In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


In [2]:
df = pd.read_csv("Dataset/homeprice1.csv")
df.head()

town  area   price
0  monroe township  2600  550000
1  monroe township  3000  565000
2  monroe township  3200  610000
3  monroe township  3600  680000
4  monroe township  4000  725000

In [3]:
from sklearn.preprocessing import LabelEncoder
le =LabelEncoder()
dfle  =df
dfle['town'] =le.fit_transform(dfle['town'])
print(dfle)

    town  area   price
0      0  2600  550000
1      0  3000  565000
2      0  3200  610000
3      0  3600  680000
4      0  4000  725000
5      2  2600  585000
6      2  2800  615000
7      2  3300  650000
8      2  3600  710000
9      1  2600  575000
10     1  2900  600000
11     1  3100  620000
12     1  3600  695000


In [20]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ct = ColumnTransformer([('town',OneHotEncoder(),[0])],remainder='passthrough')


In [ ]:
x = dfle[['town','area']]
x =ct.fit_transform(x)
print (x)



[[1.0e+00 0.0e+00 0.0e+00 2.6e+03]
 [1.0e+00 0.0e+00 0.0e+00 3.0e+03]
 [1.0e+00 0.0e+00 0.0e+00 3.2e+03]
 [1.0e+00 0.0e+00 0.0e+00 3.6e+03]
 [1.0e+00 0.0e+00 0.0e+00 4.0e+03]
 [0.0e+00 0.0e+00 1.0e+00 2.6e+03]
 [0.0e+00 0.0e+00 1.0e+00 2.8e+03]
 [0.0e+00 0.0e+00 1.0e+00 3.3e+03]
 [0.0e+00 0.0e+00 1.0e+00 3.6e+03]
 [0.0e+00 1.0e+00 0.0e+00 2.6e+03]
 [0.0e+00 1.0e+00 0.0e+00 2.9e+03]
 [0.0e+00 1.0e+00 0.0e+00 3.1e+03]
 [0.0e+00 1.0e+00 0.0e+00 3.6e+03]]


In [6]:
X = x[:,1:]
y = dfle['price'].values
print(X)
print(y)

[[0.0e+00 0.0e+00 2.6e+03]
 [0.0e+00 0.0e+00 3.0e+03]
 [0.0e+00 0.0e+00 3.2e+03]
 [0.0e+00 0.0e+00 3.6e+03]
 [0.0e+00 0.0e+00 4.0e+03]
 [0.0e+00 1.0e+00 2.6e+03]
 [0.0e+00 1.0e+00 2.8e+03]
 [0.0e+00 1.0e+00 3.3e+03]
 [0.0e+00 1.0e+00 3.6e+03]
 [1.0e+00 0.0e+00 2.6e+03]
 [1.0e+00 0.0e+00 2.9e+03]
 [1.0e+00 0.0e+00 3.1e+03]
 [1.0e+00 0.0e+00 3.6e+03]]
[550000 565000 610000 680000 725000 585000 615000 650000 710000 575000
 600000 620000 695000]


In [7]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
model = LinearRegression()
Xtrain,Xtest,ytrain,ytest = train_test_split(X,y,test_size=0.2)

In [8]:
model.fit(Xtrain,ytrain)

LinearRegression()

In [9]:
model.predict([[0,0,2300]])

array([501428.57142857])

In [47]:
data = pd.read_csv("Dataset/carprices.csv")
data.head()

Car Model  Mileage  Sell Price($)  Age(yrs)
0    BMW X5    69000          18000         6
1    BMW X5    35000          34000         3
2    BMW X5    57000          26100         5
3    BMW X5    22500          40000         2
4    BMW X5    46000          31500         4

In [50]:
dummies = pd.get_dummies(data['Car Model']).astype('int') 
print(dummies)


    Audi A5  BMW X5  Mercedez Benz C class
0         0       1                      0
1         0       1                      0
2         0       1                      0
3         0       1                      0
4         0       1                      0
5         1       0                      0
6         1       0                      0
7         1       0                      0
8         1       0                      0
9         0       0                      1
10        0       0                      1
11        0       0                      1
12        0       0                      1


In [53]:
merge = pd.concat([data,dummies],axis = 'columns')
merge =merge.drop(['Car Model','Audi A5'],axis ='columns')
print(merge)

    Mileage  Sell Price($)  Age(yrs)  BMW X5  Mercedez Benz C class
0     69000          18000         6       1                      0
1     35000          34000         3       1                      0
2     57000          26100         5       1                      0
3     22500          40000         2       1                      0
4     46000          31500         4       1                      0
5     59000          29400         5       0                      0
6     52000          32000         5       0                      0
7     72000          19300         6       0                      0
8     91000          12000         8       0                      0
9     67000          22000         6       0                      1
10    83000          20000         7       0                      1
11    79000          21000         7       0                      1
12    59000          33000         5       0                      1


In [61]:
x = merge[['Mileage', 'Age(yrs)', 'BMW X5', 'Mercedez Benz C class']]
y= merge['Sell Price($)']

In [67]:
reg = LinearRegression()
xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size=0.25)
reg.fit(xtrain,ytrain)

LinearRegression()

In [70]:
print(reg.coef_)
print(reg.intercept_)
print(ytest)
print(reg.predict(xtest))

[-6.75427350e-01  2.89375000e+03 -2.79433761e+03  2.28563034e+03]
52667.73504273504
0     18000
9     22000
8     12000
12    33000
Name: Sell Price($), dtype: int64
[20631.41025641 27062.23290598 14353.84615385 29571.9017094 ]


In [73]:
reg.predict([[45000,4,0,0]])

c:\Users\DELL\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([33848.5042735])

In [71]:
print(reg.score(xtest,ytest))

0.7876763725753501
